services:
  - type: web
    name: pixelo-app
    env: python
    plan: free
    buildCommand: bash build.sh
    startCommand: bash start.sh
    envVars:
      - key: DEBUG
        value: "False"
      - key: SERVE_MEDIA
        value: "1"
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: CLOUDINARY_VIDEO_MAX_BYTES
        value: "104857600"
      - key: RUN_MEDIA_MIGRATION
        value: "1"
      - key: RUN_MEDIA_PATH_FIX
        value: "1"
      - key: RUN_CLEAR_MISSING_MEDIA
        value: "1"
      - key: RUN_CLEAR_MISSING_MEDIA_REMOTE
        value: "1"
