services:
  - type: web
    name: pixelo-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: DEBUG
        value: "False"
      - key: SERVE_MEDIA
        value: "1"
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
