"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

import os
import importlib.util
import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    if os.getenv("DEBUG", "True").lower() in ("1", "true", "yes", "on"):
        SECRET_KEY = "dev-insecure-change-me"
    else:
        raise ImproperlyConfigured("SECRET_KEY is required when DEBUG is False.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() in ("1", "true", "yes", "on")

DEFAULT_ALLOWED_HOSTS = ["localhost", "127.0.0.1", "192.168.29.185", "pixelo-app.onrender.com"]
raw_allowed_hosts = os.getenv("ALLOWED_HOSTS", "")
ALLOWED_HOSTS = []
if raw_allowed_hosts:
    # Support space- or comma-separated values.
    tokens = raw_allowed_hosts.replace(",", " ").split()
    ALLOWED_HOSTS.extend(tokens)
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = DEFAULT_ALLOWED_HOSTS[:]

RENDER_EXTERNAL_HOSTNAME = os.getenv("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# CSRF trusted origins
raw_csrf_origins = os.getenv("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = []
if raw_csrf_origins:
    # Support space- or comma-separated values.
    tokens = raw_csrf_origins.replace(",", " ").split()
    for token in tokens:
        token = token.strip()
        if not token:
            continue
        if "://" not in token:
            token = f"https://{token}"
        CSRF_TRUSTED_ORIGINS.append(token)
elif RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS = [f"https://{RENDER_EXTERNAL_HOSTNAME}"]

# Normalize / de-dup
clean_hosts = []
for h in ALLOWED_HOSTS:
    h = h.strip()
    if not h:
        continue
    if "://" in h:
        h = h.split("://", 1)[1]
    h = h.rstrip("/")
    clean_hosts.append(h)
ALLOWED_HOSTS = list(dict.fromkeys(clean_hosts))

if os.getenv("LOG_ALLOWED_HOSTS", "0").lower() in ("1", "true", "yes", "on"):
    print(f"Resolved ALLOWED_HOSTS: {ALLOWED_HOSTS}")

# If CSRF_TRUSTED_ORIGINS is still empty, derive from ALLOWED_HOSTS so
# file uploads via fetch() work on production domains.
if not CSRF_TRUSTED_ORIGINS:
    derived = []
    for host in ALLOWED_HOSTS:
        if not host:
            continue
        if host == "*":
            continue
        is_local = host in ("localhost", "127.0.0.1") or host.startswith("192.168.") or host.startswith("10.") or host.startswith("172.")
        if is_local or DEBUG:
            derived.append(f"http://{host}")
        derived.append(f"https://{host}")
    CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(derived))


# Application definition

INSTALLED_APPS = [
    'myapp.apps.MyappConfig',
    'channels',
    'cloudinary',
    'cloudinary_storage',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'daphne',
    'django.contrib.staticfiles',
]

CLOUDINARY_URL = (os.getenv("CLOUDINARY_URL") or "").strip()
CLOUDINARY_ENABLED = CLOUDINARY_URL.startswith("cloudinary://")
HAS_CLOUDINARY_STORAGE = importlib.util.find_spec("cloudinary_storage") is not None
HAS_CLOUDINARY = importlib.util.find_spec("cloudinary") is not None
CAN_USE_CLOUDINARY = CLOUDINARY_ENABLED and HAS_CLOUDINARY_STORAGE and HAS_CLOUDINARY

# Add Cloudinary apps only when available and properly configured.
if CAN_USE_CLOUDINARY:
    INSTALLED_APPS = ['cloudinary_storage', 'cloudinary'] + INSTALLED_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'myapp.context_processors.global_counts',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'
ASGI_APPLICATION = 'myproject.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Use DATABASE_URL (e.g. Render Postgres) when provided.
DATABASE_URL = os.getenv("DATABASE_URL")
if DATABASE_URL:
    DATABASES["default"] = dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
        ssl_require=True,
    )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_URL = '/static/'
# Do not add myapp/static to STATICFILES_DIRS because it is already
# discovered via INSTALLED_APPS, which causes duplicate collection.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Compatibility for third-party packages expecting STATICFILES_STORAGE
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Storage backends
# - staticfiles: WhiteNoise for hashed static assets in production
# - default: Cloudinary for uploads when configured, else local filesystem
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
}

# Cloudinary for user uploads (images/videos) when CLOUDINARY_URL is valid.
if CAN_USE_CLOUDINARY:
    # Use a custom storage that picks image/video resource types based on file extension.
    STORAGES["default"] = {
        "BACKEND": "myapp.storage.MediaCloudinaryAutoStorage",
    }

# Security settings for production behind a proxy (Render/Heroku/etc.)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", str(not DEBUG)).lower() in ("1", "true", "yes", "on")
SESSION_COOKIE_SECURE = os.getenv("SESSION_COOKIE_SECURE", str(not DEBUG)).lower() in ("1", "true", "yes", "on")
CSRF_COOKIE_SECURE = os.getenv("CSRF_COOKIE_SECURE", str(not DEBUG)).lower() in ("1", "true", "yes", "on")
SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "0" if DEBUG else "3600"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv("SECURE_HSTS_INCLUDE_SUBDOMAINS", "True").lower() in ("1", "true", "yes", "on")
SECURE_HSTS_PRELOAD = os.getenv("SECURE_HSTS_PRELOAD", "True").lower() in ("1", "true", "yes", "on")
SECURE_REFERRER_POLICY = "same-origin"

LOGIN_URL = '/login/'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}

YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY", "")


# settings.py

import os
from pathlib import Path
import cloudinary   # 👈 yahan import karo

# baaki settings...

cloudinary.config(
    cloud_name = "dhh5tfygz",
    api_key = "544393381655137",
    api_secret = "E_b_1af7MJwp9IRdI4DdIDV9tdg"
)

# 👇 ye bhi ensure karo
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'