"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

import os
import importlib.util
import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    if os.getenv("DEBUG", "True").lower() in ("1", "true", "yes", "on"):
        SECRET_KEY = "dev-insecure-change-me"
    else:
        raise ImproperlyConfigured("SECRET_KEY is required when DEBUG is False.")

# SECURITY WARNING: don't run with debug turned on in production!
# Default to True for local dev when DEBUG is not provided.
DEBUG = os.getenv("DEBUG", "True").lower() in ("1", "true", "yes", "on")

DEFAULT_ALLOWED_HOSTS = ["localhost", "127.0.0.1", "192.168.29.185", "pixelo-app.onrender.com"]
raw_allowed_hosts = os.getenv("ALLOWED_HOSTS", "")
ALLOWED_HOSTS = []
if raw_allowed_hosts:
    # Support space- or comma-separated values.
    tokens = raw_allowed_hosts.replace(",", " ").split()
    ALLOWED_HOSTS.extend(tokens)
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = DEFAULT_ALLOWED_HOSTS[:]

RENDER_EXTERNAL_HOSTNAME = os.getenv("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# CSRF trusted origins
raw_csrf_origins = os.getenv("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = []
if raw_csrf_origins:
    # Support space- or comma-separated values.
    tokens = raw_csrf_origins.replace(",", " ").split()
    for token in tokens:
        token = token.strip()
        if not token:
            continue
        if "://" not in token:
            token = f"https://{token}"
        CSRF_TRUSTED_ORIGINS.append(token)
elif RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS = [f"https://{RENDER_EXTERNAL_HOSTNAME}"]

# Normalize / de-dup
clean_hosts = []
for h in ALLOWED_HOSTS:
    h = h.strip()
    if not h:
        continue
    if "://" in h:
        h = h.split("://", 1)[1]
    h = h.rstrip("/")
    clean_hosts.append(h)
ALLOWED_HOSTS = list(dict.fromkeys(clean_hosts))

if os.getenv("LOG_ALLOWED_HOSTS", "0").lower() in ("1", "true", "yes", "on"):
    print(f"Resolved ALLOWED_HOSTS: {ALLOWED_HOSTS}")

# If CSRF_TRUSTED_ORIGINS is still empty, derive from ALLOWED_HOSTS so
# file uploads via fetch() work on production domains.
if not CSRF_TRUSTED_ORIGINS:
    derived = []
    for host in ALLOWED_HOSTS:
        if not host:
            continue
        if host == "*":
            continue
        is_local = host in ("localhost", "127.0.0.1","https://pixelo-app.onrender.com") or host.startswith("192.168.") or host.startswith("10.") or host.startswith("172.")
        if is_local or DEBUG:
            derived.append(f"http://{host}")
            # For localhost and 127.0.0.1 in development, also add common ports
            if DEBUG and host in ("localhost", "127.0.0.1"):
                for port in [8000, 8001, 3000, 5000, 5173]:
                    derived.append(f"http://{host}:{port}")
        derived.append(f"https://{host}")
    CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(derived))


# Application definition

INSTALLED_APPS = [
    'myapp.apps.MyappConfig',
    'channels',
    'cloudinary',
    'cloudinary_storage',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'daphne',
    'django.contrib.staticfiles',
]

CLOUDINARY_URL = (os.getenv("CLOUDINARY_URL") or "").strip()
CLOUDINARY_CLOUD_NAME = (os.getenv("CLOUDINARY_CLOUD_NAME") or "").strip()
CLOUDINARY_API_KEY = (os.getenv("CLOUDINARY_API_KEY") or "").strip()
CLOUDINARY_API_SECRET = (os.getenv("CLOUDINARY_API_SECRET") or "").strip()
CLOUDINARY_UPLOAD_PRESET = (os.getenv("CLOUDINARY_UPLOAD_PRESET") or "").strip()

# Cloudinary is enabled when credentials are available.
CAN_USE_CLOUDINARY = bool(
    CLOUDINARY_URL or (CLOUDINARY_CLOUD_NAME and CLOUDINARY_API_KEY and CLOUDINARY_API_SECRET)
)

# Cloudinary storage configuration
# Only define CLOUDINARY_STORAGE when explicit credentials are present.
# If CLOUDINARY_URL is set, cloudinary_storage can read from it directly.
if CLOUDINARY_CLOUD_NAME and CLOUDINARY_API_KEY and CLOUDINARY_API_SECRET:
    CLOUDINARY_STORAGE = {
        "CLOUD_NAME": CLOUDINARY_CLOUD_NAME,
        "API_KEY": CLOUDINARY_API_KEY,
        "API_SECRET": CLOUDINARY_API_SECRET,
        "SECURE": True,
    }
    if CLOUDINARY_UPLOAD_PRESET:
        CLOUDINARY_STORAGE["UPLOAD_PRESET"] = CLOUDINARY_UPLOAD_PRESET

# Configure explicit Cloudinary credentials when available.
if CAN_USE_CLOUDINARY:
    try:
        import cloudinary
        if CLOUDINARY_URL:
            cloudinary.config(cloudinary_url=CLOUDINARY_URL, secure=True)
        else:
            cloudinary.config(
                cloud_name=CLOUDINARY_CLOUD_NAME,
                api_key=CLOUDINARY_API_KEY,
                api_secret=CLOUDINARY_API_SECRET,
                secure=True,
            )
    except Exception:
        # Fail soft: the storage backend will surface configuration errors.
        pass

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'myapp.middleware.ClientDisconnectMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # Custom middleware to add Content-Security-Policy frame-ancestors
    # when configured via ALLOW_FRAMING_FROM environment variable.
    'myapp.middleware.AllowFrameAncestorsMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'myapp.context_processors.global_counts',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'
ASGI_APPLICATION = 'myproject.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Use DATABASE_URL (e.g. Render Postgres) when provided.
DATABASE_URL = os.getenv("DATABASE_URL")
if DATABASE_URL:
    DATABASES["default"] = dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=0,
        ssl_require=True,
    )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_URL = '/static/'
# Do not add myapp/static to STATICFILES_DIRS because it is already
# discovered via INSTALLED_APPS, which causes duplicate collection.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = "whitenoise.storage.StaticFilesStorage"
WHITENOISE_SKIP_COMPRESS = True

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default storage backend (overridden by STORAGES when configured).
# Keep it aligned with CAN_USE_CLOUDINARY to avoid misconfigured uploads.
# Use MediaCloudinaryAutoStorage to properly route videos with resource_type="video"
DEFAULT_FILE_STORAGE = (
    "myapp.storage.MediaCloudinaryAutoStorage"
    if CAN_USE_CLOUDINARY
    else "django.core.files.storage.FileSystemStorage"
)

# Allow serving media files directly from Django in production when needed.
# Use with care on hosted environments; prefer Cloudinary for durability.
_raw_serve_media = (os.getenv("SERVE_MEDIA", "") or "").strip().lower()
if _raw_serve_media:
    SERVE_MEDIA = _raw_serve_media in ("1", "true", "yes", "on")
else:
    # Auto-enable media serving when Cloudinary is not configured so uploads
    # remain visible on hosted environments like Render.
    SERVE_MEDIA = DEBUG or (not CAN_USE_CLOUDINARY)

# Upload limits (bytes). Raise to allow long videos; override via env as needed.
# FILE_UPLOAD_MAX_MEMORY_SIZE: Peak memory usage per file during upload
# - 500MB allows handling large video files efficiently on hosted platforms
# - Files larger than this will be streamed to disk (slower but conserves memory)
FILE_UPLOAD_MAX_MEMORY_SIZE = int(
    os.getenv("FILE_UPLOAD_MAX_MEMORY_SIZE", str(500 * 1024 * 1024))
)
# DATA_UPLOAD_MAX_MEMORY_SIZE: Total POST data (all files + fields) limit
# Raised to support very large uploads when using the server as a proxy.
DATA_UPLOAD_MAX_MEMORY_SIZE = int(
    os.getenv("DATA_UPLOAD_MAX_MEMORY_SIZE", str(50 * 1024 * 1024 * 1024))
)

# App-level upload guards (bytes). Keep these <= platform limits to avoid 502s/timeouts.
MAX_REEL_UPLOAD_BYTES = int(
    os.getenv("MAX_REEL_UPLOAD_BYTES", str(50 * 1024 * 1024))
)
MAX_POST_UPLOAD_BYTES = int(
    os.getenv("MAX_POST_UPLOAD_BYTES", str(50 * 1024 * 1024 * 1024))
)
# Chunk size for large uploads (bytes). Optimize for speed vs memory/proxy timeouts.
# 5MB chunks are optimal for most network conditions and provide good throughput.
UPLOAD_CHUNK_SIZE = int(
    os.getenv("UPLOAD_CHUNK_SIZE", str(5 * 1024 * 1024))
)
# Only attempt server-side duration checks for reasonably sized files (up to 500MB).
# Extended to help detect long videos that should be converted to posts.
MAX_REEL_DURATION_CHECK_BYTES = int(
    os.getenv("MAX_REEL_DURATION_CHECK_BYTES", str(500 * 1024 * 1024))
)

# Optional: allow the app to be embedded in an iframe from specific origins.
# Set env `ALLOW_FRAMING_FROM` to a space- or comma-separated list of origins
# (e.g. "https://example.com https://partner.example") or use 'self'.
raw_allow_framing = os.getenv("ALLOW_FRAMING_FROM", "").strip()
ALLOW_FRAMING_FROM = []
if raw_allow_framing:
    tokens = raw_allow_framing.replace(",", " ").split()
    ALLOW_FRAMING_FROM = [t.strip() for t in tokens if t.strip()]

# If ALLOW_FRAMING_FROM is set, ensure those origins are trusted for CSRF
# so uploads from embedded frames or partner pages can post back safely.
if ALLOW_FRAMING_FROM:
    try:
        extras = []
        for a in ALLOW_FRAMING_FROM:
            if not a:
                continue
            if a in ("'self'", "self"):
                # 'self' is not a valid CSRF_TRUSTED_ORIGINS entry
                continue
            if "://" in a:
                extras.append(a)
            else:
                extras.append(f"https://{a}")
        # Merge while preserving existing order and uniqueness
        CSRF_TRUSTED_ORIGINS = list(dict.fromkeys((CSRF_TRUSTED_ORIGINS or []) + extras))
    except Exception:
        # Fail soft: do not raise on settings parsing
        pass

# Direct-to-Cloudinary upload controls
DIRECT_UPLOAD_MIN_BYTES = int(
    os.getenv("DIRECT_UPLOAD_MIN_BYTES", str(15 * 1024 * 1024))
)
MAX_DIRECT_UPLOAD_BYTES = int(
    os.getenv("MAX_DIRECT_UPLOAD_BYTES", str(50 * 1024 * 1024 * 1024))
)
# Allow unsigned direct uploads only when explicitly enabled.
ALLOW_UNSIGNED_UPLOAD = os.getenv("ALLOW_UNSIGNED_UPLOAD", "").lower() in ("1", "true", "yes", "on")

# File upload handler: Use memory for files < 500MB, disk streaming for larger files
# This prevents memory exhaustion on platform with constrained resources like Render.com
FILE_UPLOAD_HANDLERS = [
    "django.core.files.uploadhandler.MemoryFileUploadHandler",
    "myapp.upload_handler.LargeVideoUploadHandler",
]

# Storage backends
# - staticfiles: WhiteNoise for hashed static assets in production
# - default: Cloudinary for uploads when configured, else local filesystem

if CAN_USE_CLOUDINARY:
    # Use a custom storage that picks image/video resource types based on file extension.
    STORAGES = {
        "default": {
            "BACKEND": "myapp.storage.MediaCloudinaryAutoStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.StaticFilesStorage",
        },
    }
else:
    # Local filesystem storage for uploads (dev or when Cloudinary isn't configured).
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
            "OPTIONS": {
                "location": MEDIA_ROOT,
                "base_url": MEDIA_URL,
            },
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.StaticFilesStorage",
        },
    }

# Security settings for production behind a proxy (Render/Heroku/etc.)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", str(not DEBUG)).lower() in ("1", "true", "yes", "on")
SESSION_COOKIE_SECURE = os.getenv("SESSION_COOKIE_SECURE", str(not DEBUG)).lower() in ("1", "true", "yes", "on")
CSRF_COOKIE_SECURE = os.getenv("CSRF_COOKIE_SECURE", str(not DEBUG)).lower() in ("1", "true", "yes", "on")
SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "0" if DEBUG else "3600"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv("SECURE_HSTS_INCLUDE_SUBDOMAINS", "True").lower() in ("1", "true", "yes", "on")
SECURE_HSTS_PRELOAD = os.getenv("SECURE_HSTS_PRELOAD", "True").lower() in ("1", "true", "yes", "on")
SECURE_REFERRER_POLICY = "same-origin"

# Allow CDN resources for CSS, fonts, and scripts (for Tracking Prevention compatibility)
# This prevents "Tracking Prevention blocked access to storage" errors
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"

LOGIN_URL = '/login/'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}

YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY", "")


# NOTE: Cloudinary credentials should be provided via environment variables.

