# Generated by Django 5.2.11 on 2026-02-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_message_notification_story_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('post', 'Post'), ('reel', 'Reel')], default='post', max_length=10),
        ),
    ]
