# Generated by Django 5.2.11 on 2026-04-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0023_notification_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="duration",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
